experiment_name: toy_bc_non_smoke

state:
  type: states

action:
  type: left_stick

reference_trajectory:
  video: four_room_human_00_video.mp4
  inputs: four_room_human_00_inputs.json

agent:
  type: toy_bc
  seed: 5678

wandb:
  username: t-luschaefer
  project: Lukas_Sandbox
  eval_group: TestRuns
  save_dir: ./logs
  log_model: false
  offline: true
  train_name: toy_bc_non_smoke
  eval_name: toy_bc_non_smoke/eval
  train_group: TestRuns

pytorch_lightning:
  seed_everything: 5678
  trainer:
    strategy: auto
    accelerator: gpu
    enable_checkpointing: true
    enable_progress_bar:
    enable_model_summary: true
    max_steps: 10000
  optimizer: adam
  optimizer_kwargs:
    lr: 0.001
  scheduler: torch.optim.lr_scheduler.LinearLR
  scheduler_kwargs:
    start_factor: 1.0
    end_factor: 0.001
    total_iters: 50000

callbacks:
  checkpoint_callback: true
  checkpoint_callback_kwargs:
    save_top_k: -1
    every_n_epochs: 0
    every_n_train_steps: 1000
    filename: "{step}"
    verbose: false
    save_last: true
    save_on_train_epoch_end: true
    dirpath: checkpoints/toy_bc_non_smoke

data:
  train_data_dir: $REPO_DIRECTORY/datasets/four_room_human_data/
  num_train_samples: 16
  num_validation_samples: 4
  shuffle_trajectories: true
  batch_size: 16
  num_workers: 1
  history: 0
  history_slice_specs:
    class_name: LinearSlicer
    num_samples: 0
  padding_strategy: zero
  alignment_strategy: causal_action_frame_alignment

model:
  algorithm: bc
  input_format: state_only
  submodels:
    state_encoder:
      class_name: StateEncoder
      init_args:
        encoder_model:
          class_name: NetworkBlock
          init_args:
            network_config:
              - type: linear
                size: 512
                num_layers: 1
              - type: relu
              - type: linear
                size: 1024
                num_layers: 1
              - type: relu
              - type: linear
                size: 256
                num_layers: 1
              - type: relu
              - type: batch_norm

    policy_head:
      class_name: PolicyHead
      init_args:
        policy_model:
          class_name: PolicyNetwork
          init_args:
            base_model:
              class_name: NetworkBlock
              init_args:
                network_config:
                  - type: linear
                    size: 256
                    num_layers: 1
                  - type: relu
                collapse_sequence: true
        action_loss:
          continuous_loss: l1
